import {test,expect} from '@playwright/test'
test('product price',async({page})=>{
    await page.goto('https://demoblaze.com/index.html')
    await page.locator('a:has-text("Samsung galaxy s6")').click()
    await expect(page).toHaveURL('https://demoblaze.com/prod.html?idp_=1')
    page.once('dialog',async(dialog)=>{
        expect(dialog.message()).toBe('Product added')
         await dialog.accept()
    })
    await page.locator('a:has-text("Add to cart")').click()
    await page.locator('#cartur').click()
    await expect(page).toHaveURL('https://demoblaze.com/cart.html')
    await page.getByRole('button', { name: 'Place Order' }).click()
    await page.locator("#name").fill('useless useless')
    await page.locator("#country").fill('india')
    await page.locator("#city").fill('chennai')
    await page.locator("#card").fill('9938839393')
    await page.locator("#month").fill('JAN')
    await page.locator("#year").fill('2026')
    await page.locator('button:has-text("Purchase")').click()
    const product_detail=page.locator('p.lead.text-muted')
    const text =await product_detail.innerText()
    console.log(text)
    await page.getByRole('button', { name: 'OK' }).click()
})